micronaut:
  application:
    name: keymanagerRest

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    keyManager:
      address: 'localhost:50051'

jackson:
  serialization:
    writeDatesAsTimestamps: false